[project]
name = 'Relic-Hunt-and-Preservation-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.authentication-process]
path = 'contracts/authentication-process.clar'
clarity_version = 2
epoch = 2.5

[contracts.cosmic-relic-marketplace]
path = 'contracts/cosmic-relic-marketplace.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
